/**
 * lnbits client
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateExtension {
    'extId': string;
    'archive': string;
    'sourceRepo': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "extId",
            "baseName": "ext_id",
            "type": "string"
        },
        {
            "name": "archive",
            "baseName": "archive",
            "type": "string"
        },
        {
            "name": "sourceRepo",
            "baseName": "source_repo",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateExtension.attributeTypeMap;
    }
}

