/**
 * lnbits client
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateInvoiceData {
    'out'?: boolean = true;
    'amount'?: number;
    'memo'?: string;
    'unit'?: string = 'sat';
    'descriptionHash'?: string;
    'unhashedDescription'?: string;
    'expiry'?: number;
    'lnurlCallback'?: string;
    'lnurlBalanceCheck'?: string;
    'extra'?: object;
    'webhook'?: string;
    'internal'?: boolean = false;
    'bolt11'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "out",
            "baseName": "out",
            "type": "boolean"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "memo",
            "baseName": "memo",
            "type": "string"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "descriptionHash",
            "baseName": "description_hash",
            "type": "string"
        },
        {
            "name": "unhashedDescription",
            "baseName": "unhashed_description",
            "type": "string"
        },
        {
            "name": "expiry",
            "baseName": "expiry",
            "type": "number"
        },
        {
            "name": "lnurlCallback",
            "baseName": "lnurl_callback",
            "type": "string"
        },
        {
            "name": "lnurlBalanceCheck",
            "baseName": "lnurl_balance_check",
            "type": "string"
        },
        {
            "name": "extra",
            "baseName": "extra",
            "type": "object"
        },
        {
            "name": "webhook",
            "baseName": "webhook",
            "type": "string"
        },
        {
            "name": "internal",
            "baseName": "internal",
            "type": "boolean"
        },
        {
            "name": "bolt11",
            "baseName": "bolt11",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateInvoiceData.attributeTypeMap;
    }
}

