/**
 * lnbits client
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Base class for settings, allowing values to be overridden by environment variables.  This is useful in production for secrets you do not wish to save in code, it plays nicely with docker(-compose), Heroku and any 12 factor app design.
*/
export class EditableSettings {
    'lightningInvoiceExpiry'?: number = 600;
    'boltzNetwork'?: string = 'main';
    'boltzUrl'?: string = 'https://boltz.exchange/api';
    'boltzMempoolSpaceUrl'?: string = 'https://mempool.space';
    'boltzMempoolSpaceUrlWs'?: string = 'wss://mempool.space';
    'lntipsApiEndpoint'?: string;
    'lntipsApiKey'?: string;
    'lntipsAdminKey'?: string;
    'lntipsInvoiceKey'?: string;
    'sparkUrl'?: string;
    'sparkToken'?: string;
    'opennodeApiEndpoint'?: string;
    'opennodeKey'?: string;
    'opennodeAdminKey'?: string;
    'opennodeInvoiceKey'?: string;
    'lnpayApiEndpoint'?: string;
    'lnpayApiKey'?: string;
    'lnpayWalletKey'?: string;
    'lnpayAdminKey'?: string;
    'lndGrpcEndpoint'?: string;
    'lndGrpcCert'?: string;
    'lndGrpcPort'?: number;
    'lndGrpcAdminMacaroon'?: string;
    'lndGrpcInvoiceMacaroon'?: string;
    'lndGrpcMacaroon'?: string;
    'lndGrpcMacaroonEncrypted'?: string;
    'lndRestEndpoint'?: string;
    'lndRestCert'?: string;
    'lndRestMacaroon'?: string;
    'lndRestMacaroonEncrypted'?: string;
    'lndCert'?: string;
    'lndAdminMacaroon'?: string;
    'lndInvoiceMacaroon'?: string;
    'lndRestAdminMacaroon'?: string;
    'lndRestInvoiceMacaroon'?: string;
    'eclairUrl'?: string;
    'eclairPass'?: string;
    'corelightningRpc'?: string;
    'clightningRpc'?: string;
    'clicheEndpoint'?: string;
    'lnbitsEndpoint'?: string = 'https://legend.lnbits.com';
    'lnbitsKey'?: string;
    'lnbitsAdminKey'?: string;
    'lnbitsInvoiceKey'?: string;
    'fakeWalletSecret'?: string = 'ToTheMoon1';
    'lnbitsBackendWalletClass'?: string = 'VoidWallet';
    'lnbitsRateLimitNo'?: string = '200';
    'lnbitsRateLimitUnit'?: string = 'minute';
    'lnbitsAllowedIps'?: Array<string>;
    'lnbitsBlockedIps'?: Array<string>;
    'lnbitsNotifications'?: boolean = false;
    'lnbitsKillswitch'?: boolean = false;
    'lnbitsKillswitchInterval'?: number = 60;
    'lnbitsWatchdog'?: boolean = false;
    'lnbitsWatchdogInterval'?: number = 60;
    'lnbitsWatchdogDelta'?: number = 1000000;
    'lnbitsStatusManifest'?: string = 'https://raw.githubusercontent.com/lnbits/lnbits-status/main/manifest.json';
    'lnbitsBaseurl'?: string = 'http://127.0.0.1:5000/';
    'lnbitsReserveFeeMin'?: number = 2000;
    'lnbitsReserveFeePercent'?: number = 1.0;
    'lnbitsServiceFee'?: number = 0;
    'lnbitsHideApi'?: boolean = false;
    'lnbitsDenomination'?: string = 'sats';
    'lnbitsSiteTitle'?: string = 'LNbits';
    'lnbitsSiteTagline'?: string = 'free and open-source lightning wallet';
    'lnbitsSiteDescription'?: string;
    'lnbitsDefaultWalletName'?: string = 'LNbits wallet';
    'lnbitsThemeOptions'?: Array<string>;
    'lnbitsCustomLogo'?: string;
    'lnbitsAdSpaceTitle'?: string = 'Supported by';
    'lnbitsAdSpace'?: string = 'https://shop.lnbits.com/;/static/images/lnbits-shop-light.png;/static/images/lnbits-shop-dark.png';
    'lnbitsAdSpaceEnabled'?: boolean = false;
    'lnbitsAllowedCurrencies'?: Array<string>;
    'lnbitsAdminExtensions'?: Array<string>;
    'lnbitsExtensionsManifests'?: Array<string>;
    'lnbitsAdminUsers'?: Array<string>;
    'lnbitsAllowedUsers'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lightningInvoiceExpiry",
            "baseName": "lightning_invoice_expiry",
            "type": "number"
        },
        {
            "name": "boltzNetwork",
            "baseName": "boltz_network",
            "type": "string"
        },
        {
            "name": "boltzUrl",
            "baseName": "boltz_url",
            "type": "string"
        },
        {
            "name": "boltzMempoolSpaceUrl",
            "baseName": "boltz_mempool_space_url",
            "type": "string"
        },
        {
            "name": "boltzMempoolSpaceUrlWs",
            "baseName": "boltz_mempool_space_url_ws",
            "type": "string"
        },
        {
            "name": "lntipsApiEndpoint",
            "baseName": "lntips_api_endpoint",
            "type": "string"
        },
        {
            "name": "lntipsApiKey",
            "baseName": "lntips_api_key",
            "type": "string"
        },
        {
            "name": "lntipsAdminKey",
            "baseName": "lntips_admin_key",
            "type": "string"
        },
        {
            "name": "lntipsInvoiceKey",
            "baseName": "lntips_invoice_key",
            "type": "string"
        },
        {
            "name": "sparkUrl",
            "baseName": "spark_url",
            "type": "string"
        },
        {
            "name": "sparkToken",
            "baseName": "spark_token",
            "type": "string"
        },
        {
            "name": "opennodeApiEndpoint",
            "baseName": "opennode_api_endpoint",
            "type": "string"
        },
        {
            "name": "opennodeKey",
            "baseName": "opennode_key",
            "type": "string"
        },
        {
            "name": "opennodeAdminKey",
            "baseName": "opennode_admin_key",
            "type": "string"
        },
        {
            "name": "opennodeInvoiceKey",
            "baseName": "opennode_invoice_key",
            "type": "string"
        },
        {
            "name": "lnpayApiEndpoint",
            "baseName": "lnpay_api_endpoint",
            "type": "string"
        },
        {
            "name": "lnpayApiKey",
            "baseName": "lnpay_api_key",
            "type": "string"
        },
        {
            "name": "lnpayWalletKey",
            "baseName": "lnpay_wallet_key",
            "type": "string"
        },
        {
            "name": "lnpayAdminKey",
            "baseName": "lnpay_admin_key",
            "type": "string"
        },
        {
            "name": "lndGrpcEndpoint",
            "baseName": "lnd_grpc_endpoint",
            "type": "string"
        },
        {
            "name": "lndGrpcCert",
            "baseName": "lnd_grpc_cert",
            "type": "string"
        },
        {
            "name": "lndGrpcPort",
            "baseName": "lnd_grpc_port",
            "type": "number"
        },
        {
            "name": "lndGrpcAdminMacaroon",
            "baseName": "lnd_grpc_admin_macaroon",
            "type": "string"
        },
        {
            "name": "lndGrpcInvoiceMacaroon",
            "baseName": "lnd_grpc_invoice_macaroon",
            "type": "string"
        },
        {
            "name": "lndGrpcMacaroon",
            "baseName": "lnd_grpc_macaroon",
            "type": "string"
        },
        {
            "name": "lndGrpcMacaroonEncrypted",
            "baseName": "lnd_grpc_macaroon_encrypted",
            "type": "string"
        },
        {
            "name": "lndRestEndpoint",
            "baseName": "lnd_rest_endpoint",
            "type": "string"
        },
        {
            "name": "lndRestCert",
            "baseName": "lnd_rest_cert",
            "type": "string"
        },
        {
            "name": "lndRestMacaroon",
            "baseName": "lnd_rest_macaroon",
            "type": "string"
        },
        {
            "name": "lndRestMacaroonEncrypted",
            "baseName": "lnd_rest_macaroon_encrypted",
            "type": "string"
        },
        {
            "name": "lndCert",
            "baseName": "lnd_cert",
            "type": "string"
        },
        {
            "name": "lndAdminMacaroon",
            "baseName": "lnd_admin_macaroon",
            "type": "string"
        },
        {
            "name": "lndInvoiceMacaroon",
            "baseName": "lnd_invoice_macaroon",
            "type": "string"
        },
        {
            "name": "lndRestAdminMacaroon",
            "baseName": "lnd_rest_admin_macaroon",
            "type": "string"
        },
        {
            "name": "lndRestInvoiceMacaroon",
            "baseName": "lnd_rest_invoice_macaroon",
            "type": "string"
        },
        {
            "name": "eclairUrl",
            "baseName": "eclair_url",
            "type": "string"
        },
        {
            "name": "eclairPass",
            "baseName": "eclair_pass",
            "type": "string"
        },
        {
            "name": "corelightningRpc",
            "baseName": "corelightning_rpc",
            "type": "string"
        },
        {
            "name": "clightningRpc",
            "baseName": "clightning_rpc",
            "type": "string"
        },
        {
            "name": "clicheEndpoint",
            "baseName": "cliche_endpoint",
            "type": "string"
        },
        {
            "name": "lnbitsEndpoint",
            "baseName": "lnbits_endpoint",
            "type": "string"
        },
        {
            "name": "lnbitsKey",
            "baseName": "lnbits_key",
            "type": "string"
        },
        {
            "name": "lnbitsAdminKey",
            "baseName": "lnbits_admin_key",
            "type": "string"
        },
        {
            "name": "lnbitsInvoiceKey",
            "baseName": "lnbits_invoice_key",
            "type": "string"
        },
        {
            "name": "fakeWalletSecret",
            "baseName": "fake_wallet_secret",
            "type": "string"
        },
        {
            "name": "lnbitsBackendWalletClass",
            "baseName": "lnbits_backend_wallet_class",
            "type": "string"
        },
        {
            "name": "lnbitsRateLimitNo",
            "baseName": "lnbits_rate_limit_no",
            "type": "string"
        },
        {
            "name": "lnbitsRateLimitUnit",
            "baseName": "lnbits_rate_limit_unit",
            "type": "string"
        },
        {
            "name": "lnbitsAllowedIps",
            "baseName": "lnbits_allowed_ips",
            "type": "Array<string>"
        },
        {
            "name": "lnbitsBlockedIps",
            "baseName": "lnbits_blocked_ips",
            "type": "Array<string>"
        },
        {
            "name": "lnbitsNotifications",
            "baseName": "lnbits_notifications",
            "type": "boolean"
        },
        {
            "name": "lnbitsKillswitch",
            "baseName": "lnbits_killswitch",
            "type": "boolean"
        },
        {
            "name": "lnbitsKillswitchInterval",
            "baseName": "lnbits_killswitch_interval",
            "type": "number"
        },
        {
            "name": "lnbitsWatchdog",
            "baseName": "lnbits_watchdog",
            "type": "boolean"
        },
        {
            "name": "lnbitsWatchdogInterval",
            "baseName": "lnbits_watchdog_interval",
            "type": "number"
        },
        {
            "name": "lnbitsWatchdogDelta",
            "baseName": "lnbits_watchdog_delta",
            "type": "number"
        },
        {
            "name": "lnbitsStatusManifest",
            "baseName": "lnbits_status_manifest",
            "type": "string"
        },
        {
            "name": "lnbitsBaseurl",
            "baseName": "lnbits_baseurl",
            "type": "string"
        },
        {
            "name": "lnbitsReserveFeeMin",
            "baseName": "lnbits_reserve_fee_min",
            "type": "number"
        },
        {
            "name": "lnbitsReserveFeePercent",
            "baseName": "lnbits_reserve_fee_percent",
            "type": "number"
        },
        {
            "name": "lnbitsServiceFee",
            "baseName": "lnbits_service_fee",
            "type": "number"
        },
        {
            "name": "lnbitsHideApi",
            "baseName": "lnbits_hide_api",
            "type": "boolean"
        },
        {
            "name": "lnbitsDenomination",
            "baseName": "lnbits_denomination",
            "type": "string"
        },
        {
            "name": "lnbitsSiteTitle",
            "baseName": "lnbits_site_title",
            "type": "string"
        },
        {
            "name": "lnbitsSiteTagline",
            "baseName": "lnbits_site_tagline",
            "type": "string"
        },
        {
            "name": "lnbitsSiteDescription",
            "baseName": "lnbits_site_description",
            "type": "string"
        },
        {
            "name": "lnbitsDefaultWalletName",
            "baseName": "lnbits_default_wallet_name",
            "type": "string"
        },
        {
            "name": "lnbitsThemeOptions",
            "baseName": "lnbits_theme_options",
            "type": "Array<string>"
        },
        {
            "name": "lnbitsCustomLogo",
            "baseName": "lnbits_custom_logo",
            "type": "string"
        },
        {
            "name": "lnbitsAdSpaceTitle",
            "baseName": "lnbits_ad_space_title",
            "type": "string"
        },
        {
            "name": "lnbitsAdSpace",
            "baseName": "lnbits_ad_space",
            "type": "string"
        },
        {
            "name": "lnbitsAdSpaceEnabled",
            "baseName": "lnbits_ad_space_enabled",
            "type": "boolean"
        },
        {
            "name": "lnbitsAllowedCurrencies",
            "baseName": "lnbits_allowed_currencies",
            "type": "Array<string>"
        },
        {
            "name": "lnbitsAdminExtensions",
            "baseName": "lnbits_admin_extensions",
            "type": "Array<string>"
        },
        {
            "name": "lnbitsExtensionsManifests",
            "baseName": "lnbits_extensions_manifests",
            "type": "Array<string>"
        },
        {
            "name": "lnbitsAdminUsers",
            "baseName": "lnbits_admin_users",
            "type": "Array<string>"
        },
        {
            "name": "lnbitsAllowedUsers",
            "baseName": "lnbits_allowed_users",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return EditableSettings.attributeTypeMap;
    }
}

