/**
 * lnbits client
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Payment {
    'checkingId': string;
    'pending': boolean;
    'amount': number;
    'fee': number;
    'memo'?: string;
    'time': number;
    'bolt11': string;
    'preimage': string;
    'paymentHash': string;
    'expiry'?: number;
    'extra'?: object;
    'walletId': string;
    'webhook'?: string;
    'webhookStatus'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "checkingId",
            "baseName": "checking_id",
            "type": "string"
        },
        {
            "name": "pending",
            "baseName": "pending",
            "type": "boolean"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "number"
        },
        {
            "name": "memo",
            "baseName": "memo",
            "type": "string"
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "number"
        },
        {
            "name": "bolt11",
            "baseName": "bolt11",
            "type": "string"
        },
        {
            "name": "preimage",
            "baseName": "preimage",
            "type": "string"
        },
        {
            "name": "paymentHash",
            "baseName": "payment_hash",
            "type": "string"
        },
        {
            "name": "expiry",
            "baseName": "expiry",
            "type": "number"
        },
        {
            "name": "extra",
            "baseName": "extra",
            "type": "object"
        },
        {
            "name": "walletId",
            "baseName": "wallet_id",
            "type": "string"
        },
        {
            "name": "webhook",
            "baseName": "webhook",
            "type": "string"
        },
        {
            "name": "webhookStatus",
            "baseName": "webhook_status",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Payment.attributeTypeMap;
    }
}

